---
- name: Manage windows servers
  hosts: webservers
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
    - name: Create a new application pool in 'Started' state
      win_iis_webapppool:
       name: hello
       state: started
    - name: Create directory structure
      win_file:
       path: C:\inetpub\hello
       state: directory
    - name: Copy html over
      ansible.windows.win_copy:
       src: ./myfiles/index.html
       dest: C:\inetpub\hello\index.html
    - name: Make hello world site
      win_iis_website:
       name: HelloWorld
       state: started
       port: 80
       ip: 127.0.0.1
       application_pool: hello
       physical_path: C:\inetpub\hello
       parameters: logfile.directory:C:\inetpub\logs
      register: website
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
         $binding = HOSTNAME #(Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias Ethernet).IPAddress
         $siteName = 'HelloWorld'
         $cert = New-SelfSignedCertificate -DnsName "$binding" -CertStoreLocation "cert:\LocalMachine\My"
         $DestStore = new-object System.Security.Cryptography.X509Certificates.X509Store([System.Security.Cryptography.X509Certificates.StoreName]::Root,"localmachine")
         $DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
         $DestStore.Add($cert)
         $DestStore.Close()
         New-WebBinding -Name $siteName -Protocol "https" -Port 443 -IPAddress * -HostHeader $binding -SslFlags 1
         (Get-WebBinding -Name $siteName -Port 443 -Protocol "https" -HostHeader $binding).AddSslCertificate($cert.Thumbprint, "my")
    - name: Install DNS server features
      ansible.windows.win_feature:
        name:
          - DNS
          - RSAT-DNS-Server
        state: present
    - name: Create new domain in a new forest on the target host
      win_domain:
       dns_domain_name: jarrads.domain
       safe_mode_password: notSecure!
